#!/usr/bin/env bash
name="startup-notification"
version="0.12"
description="Application startup notification and feedback library "
source="http://www.freedesktop.org/software/startup-notification/releases/startup-notification-${version}.tar.gz"
depends="libX11,xcb-util"
group="x11.libs"

cd startup-notification-$version

setup(){
	autoreconf -fvi
    $SOURCEDIR/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

